config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'kitchens#index'

  resources :kitchens, only: [:new, :create, :show, :edit, :destroy, :update] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '野菜のおかず' }, { id: 2, name: 'お肉のおかず' }, { id: 3, name: '魚介のおかず' },
    { id: 4, name: 'ごはんもの' }, { id: 5, name: 'パスタ・グラタン' }, { id: 6, name: '麺' },
    { id: 7, name: 'サラダ' }, { id: 8, name: 'スープ・汁物' }, { id: 9, name: 'パン' }
  ]
end

app/models/kitchen.rb
class Kitchen < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre

  with_options presence: true do
    validates :name
    validates :genre_id, numericality: { other_than: 0, message: 'select' }
    validates :image
  end

  belongs_to :user
  has_many :comments
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'Full-width characters' }
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'Include both letters and numbers' }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit]

  def index
    @kitchens = Kitchen.all.order('created_at DESC')
  end

  def new
    @kitchen = Kitchen.new
  end

  def create
    @kitchen = Kitchen.create(kitchen_params)
    if @kitchen.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @kitchen = Kitchen.find(params[:id])
  end

  def edit
    @kitchen = Kitchen.find(params[:id])
    redirect_to action: :index if current_user.id != @kitchen.user_id
  end

  def destroy
    @kitchen = Kitchen.find(params[:id])
    if current_user.id == @kitchen.user_id
      @kitchen.destroy
      redirect_to root_path
    end
  end

  def update
    @kitchen = Kitchen.find(params[:id])
    if @kitchen.update(kitchen_params)
      redirect_to kitchen_path
    else
      render :edit
    end
  end

  def search
    if params[:applicationId]
      @kitchens = categories = RakutenWebService::Recipe.small_categories
    end
  end

  private

  def kitchen_params
    params.require(:kitchen).permit(:image, :name, :genre_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kitchens_helper.rb
module KitchensHelper
end

app/views/kitchens/edit.html.erb
<p class="back"><%= link_to 'もどる', root_path, class: "back-btn-edit" %></P>
<div class="request-edit">
  <h2 class="edit-title">アイデアの編集</h2>
  <%= form_with model: @kitchen, local: true do |f| %>

    <%# エラーメッセージ %>
  <%= render 'shared/error_messages', model: f.object %>

    <%# 画像 %>
  <div class="img-upload">
    <div class="img-text">アイデア画像</div>
    <div class="click-upload"><p>クリックしてファイルをアップロード</p></div>
    <%= f.file_field :image, id: "item-image" %>
  </div>
  <%# ジャンル %>
  <div class="new-genre">
    <div class="edit-gen">料理のジャンル</div>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class: "select-box", id: "select-genre"}) %> 
  </div>
  <%# リクエスト名 %>
  <div class="new-name">
    <div class="title">リクエスト料理</div>
    <%= f.text_area :name, id: "title-name", placeholder: "リクエスト料理名 (40文字まで)", maxlengs:"40" %>
  </div>
  <%# リクエスト送信ボタン・戻るボタン %>
  <div class="btn-contents">
    <%= f.submit "リクエストする", class: "btn" %>
  </div>
  <% end %>
</div>

app/views/kitchens/index.html.erb
<div class="top">
  <%# リクエスト一覧 %>
  <div class="request-contents">
    <h2 class="pick-up">IDEA</h2>
    <p class="message">詳細は画像をクリック</p>
    <ul class="request-list">
      <% @kitchens.each do |kitchen| %>
        <li class="list">
        <%# 画像 %>
          <%= link_to kitchen_path(kitchen.id) do %>
          <div class="img">
            <P><%= image_tag kitchen.image, class: "kitchen-img"%></P>
          <% end %>
          </div>
        <%# リクエストジャンル %>
          <div class="genre">
            <div class="genre-text">ジャンル</div>
             <div class="genre-name"><%= kitchen.genre.name %></div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

  <%# 楽天検索リンク %>
  <%= link_to 'レシピ検索へ', search_kitchens_path, class: "search"%>
</div>

app/views/kitchens/new.html.erb
<div class="new-request">
  <div class="new-b">
    <p><%= link_to 'もどる', root_path, class: "back-new" %></P>
  </div>

  <%= form_with model: @kitchen, local: true do |f|%>

  
  <%# エラーメッセージ %>
  <%= render 'shared/error_messages', model: f.object %>

  <div class="new">
    <div class="or">
      <h2 class="order">今日のメニュー</h2>
      <%# 画像 %>
      <div class="img-upload">
        <div class="img-text">リクエストイメージ</div>
        <div class="click-upload"><p>クリックしてファイルをアップロード</p></div>
        <%= f.file_field :image, id: "item-image" %>
      </div>
      <%# ジャンル %>
      <div class="new-gen">
        <div class="n-genre">料理のジャンル</div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class: "select-box", id: "select-genre"}) %> 
      </div>
      <%# リクエスト名 %>
      <div class="new-name">
        <div class="title">リクエスト料理</div>
        <%= f.text_area :name, id: "title-name", placeholder: "リクエスト料理名 (40文字まで)", maxlengs:"40" %>
      </div>
      <%# リクエスト送信ボタン%>
      <div class="btn-contents">
        <%= f.submit "リクエストする", class: "btn" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/kitchens/search.html.erb
<h1>楽天API</h1>
<%= form_with(url: search_kitchens_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :applicationId, placeholder: "レシピを検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<div class="result">
    <%= render partial: "shared/rakuten" %>
</div>

app/views/kitchens/show.html.erb
<div class="request-show">

 <%# ボタン %>
  <div class="show">
    <% if user_signed_in? && current_user.id == @kitchen.user_id %>
    <%= link_to 'アイデアの編集', edit_kitchen_path(@kitchen.id), method: :get, class: "request-edit-btn" %>
    <%= link_to 'アイデアの削除', kitchen_path(@kitchen.id), method: :delete, class: 'request-delete-btn' %>
    <% end %>
    <%= link_to 'もどる', root_path, class: "back-btn" %>
  </div>


  <div class="detail-table">
    <%# 画像 %>
    <div class="image">
      <div class="detail-img"><%= image_tag @kitchen.image, class: "value-img" %></div>
    </div>
    <%# リクエスト者 %>
    <div class="name">
      <div class="detail-name">なまえ
        <div class="detail-value"><%= @kitchen.user.name %></div>
      </div>
    </div>
    <%# リクエスト名 %>
    <div class="idea">
        <div class="detail-idea">ごはん
          <div class="detail-value"><%= @kitchen.name %></div>
        </div>
    </div>
    <div class="genre">
      <div class="detail-request">ジャンル</div>
      <div class="detail-value"><%= @kitchen.genre.name%></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kitchen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# リセットcss %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">

    <%# フォント用 %>
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:300" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <h1 class="cook-idea">Cook idea</h1>
    <div class="guide">
      <div class="user">
        <%# ログイン・ログアウト・新規登録 %>
        <% if user_signed_in? %>
        <%= link_to current_user.name, "#", class: "user_name-btn" %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logaut-btn" %>
        <% else %>
        <%= link_to 'ログイン', new_user_session_path, class: "login-btn" %>
        <%= link_to '新規登録', new_user_registration_path, class:"sign_in-btn" %>
        <% end %>
       </div>

        <%# リクエストへ %>
      <div class="request">
        <%= link_to 'IDEA', new_kitchen_path, class: "menu-btn" %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li> 
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<h1 class="cook-idea">Cook idea</h1>
<div class="guide">
  <div class="user">
    <%# ログイン・ログアウト・新規登録 %>
    <% if user_signed_in? %>
    <%= link_to current_user.name, "#", class: "user_name-btn" %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logaut-btn" %>
     <% else %>
    <%= link_to 'ログイン', new_user_session_path, class: "login-btn" %>
    <%= link_to '新規登録', new_user_registration_path, class:"sign_in-btn" %>
    <% end %>
  </div>

    <%# リクエストへ %>
  <div class="request">
    <%= link_to 'IDEA', new_kitchen_path, class: "menu-btn" %>
  </div>
</div>

app/views/shared/_rakuten.html.erb
<p>カテゴリー名: <%= @categoryName %></p>
<p>カテゴリーURL: <%= @categoryUrl %></p>